### ISSUE TITLE
ExecuteShowUserの実行時バグの修正

### ISSUE THREAD

**Issue by myConsciousness** [myConsciousness/twitter-bot-j#36]
# High Priotity Bug Report

## 1. Bug Details

```java
java.lang.NullPointerException: actionStatus is marked non-null but is null
	at org.thinkit.bot.twitter.result.AutoShowUserResult.<init>(AutoShowUserResult.java:41)
	at org.thinkit.bot.twitter.result.AutoShowUserResult$AutoShowUserResultBuilder.build(AutoShowUserResult.java:39)
	at org.thinkit.bot.twitter.command.AutoShowUserCommand.executeBotProcess(AutoShowUserCommand.java:62)
	at org.thinkit.bot.twitter.command.AutoShowUserCommand.executeBotProcess(AutoShowUserCommand.java:1)
	at org.thinkit.bot.twitter.command.AbstractBotCommand.execute(AbstractBotCommand.java:56)
	at org.thinkit.bot.twitter.TwitterBotJ.executeAutoShowUser(TwitterBotJ.java:70)
	at org.thinkit.bot.twitter.batch.tasklet.ExecuteAutoShowUserTasklet.executeTask(ExecuteAutoShowUserTasklet.java:70)
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.executeTaskProcess(AbstractTasklet.java:191)
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.execute(AbstractTasklet.java:131)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.runJobLauncher(BatchJobConfiguration.java:130)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.performScheduledTweetPr(BatchJobConfiguration.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

## 2. What you did caused that bug

実行時かつAutoShowUserの処理成功時にアクションステータスを設定していないため発生。

コマンド結果のアクションステータスは初期値が指定されておらず、
かつ@NonNullが指定されていたため上記の条件で実行時に失敗した。

## 3. How it should be

AutoShowUserCommandの処理成功時に必ずアクションステータスを設定するように修正する。

**Comment by myConsciousness** [comment]
@NonNullを外しコマンド結果のフィールドに初期値を設定する方法も検討する。

**Comment by myConsciousness** [comment]
修正を行いmainブランチへマージ済み。
本件はクローズとする。
