### ISSUE TITLE
ShowUserCommand実行後の後続処理でNPE

### ISSUE THREAD

**Issue by myConsciousness** [myConsciousness/twitter-bot-j#38]
# High Priotity Bug Report

## 1. Bug Details

```java
java.lang.NullPointerException: Cannot invoke "java.util.List.isEmpty()" because "actionErrors" is null
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.executeTaskProcess(AbstractTasklet.java:200)
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.execute(AbstractTasklet.java:131)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.runJobLauncher(BatchJobConfiguration.java:130)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.performScheduledTweetPr(BatchJobConfiguration.java:123)
	at jdk.internal.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
```

## 2. What you did caused that bug

コマンド処理の実行後の後続処理でNPEが発生した。
原因は抽象タスクレットの共通処理を行うために必須であったリストがnullであったため。

## 3. How it should be

共通タスクレットに至るまでにはそもそもnullを完全に取り除いたデータがある思想で設計しているため、
今回NPEが発生したリストに関しては必ず空のリストを設定するべき。

しかし、そもそもここの規格を共通化できていないことも問題なため、
ActionStatusやActionErrorといった全てのコマンドに共通の仕組みを抽象クラスとして整理したい。
この整理の対応に関しては別改善イシューを発行し並行して対応を行う。

**Comment by myConsciousness** [comment]
コマンド実行結果の共通項をまとめる対応に関しては #39 を発行した。

**Comment by myConsciousness** [comment]
本件は修正を行いmainブランチへマージ済み。
