### ISSUE TITLE
UserProfileDifference生成時のNPE

### ISSUE THREAD

**Issue by myConsciousness** [myConsciousness/twitter-bot-j#42]
# High Priotity Bug Report

## 1. Bug Details

```java
java.lang.NullPointerException: null
	at org.thinkit.common.base.precondition.Preconditions.requireNonNull(Preconditions.java:108)
	at org.thinkit.bot.twitter.util.UserProfileDifference$UserProfileDifferenceBuilder.build(UserProfileDifference.java:84)
	at org.thinkit.bot.twitter.batch.tasklet.ExecuteAutoTweetDailyReport.getUserProfileDifference(ExecuteAutoTweetDailyReport.java:142)
	at org.thinkit.bot.twitter.batch.tasklet.ExecuteAutoTweetDailyReport.executeTask(ExecuteAutoTweetDailyReport.java:89)
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.executeTaskProcess(AbstractTasklet.java:191)
	at org.thinkit.bot.twitter.batch.tasklet.AbstractTasklet.execute(AbstractTasklet.java:131)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
	at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:320)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.runJobLauncher(BatchJobConfiguration.java:130)
	at org.thinkit.bot.twitter.batch.config.BatchJobConfiguration.performScheduledTweetDailyReport(BatchJobConfiguration.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

## 2. What you did caused that bug

運用時に発生。

## 3. How it should be

以下の処理実行時にNPEが発生した。

```java
 public UserProfileDifference build() {
            Preconditions.requireNonNull(this.userProfile);
```

しかし、上記の処理に到達する前にuserProfileのnullチェックが行われているため、
本来であればここでNPEは発生しない想定。
オブジェクトを正しく設定できているか実装を確認する必要がある。

**Comment by myConsciousness** [comment]
NPEの件は修正しmainブランチへマージ済み。

実行時に成功するものの差分をとる機能が正しく機能していないため、
これを別イシューで管理し修正を行う。
